# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaraunt_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaraunt',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
