# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20170730_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
